# Generated by Django 5.1.1 on 2024-09-12 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffattendance',
            name='date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
