# Generated by Django 5.1.1 on 2024-09-12 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_position_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='staff',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.staff'),
        ),
        migrations.AlterUniqueTogether(
            name='staffattendance',
            unique_together={('staff', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='staffshift',
            unique_together={('staff', 'shift')},
        ),
    ]
